spring.application.name=Amaray
# H2 встроенная база данных
spring.datasource.url=jdbc:h2:file:./data/amaray-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA настройки
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# H2 консоль в браузере (удобно для отладки)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#jdbc:h2:file:./data/amaray-db — БД будет сохраняться в файл, а не в памяти. Это значит данные не пропадут при перезапуске приложения.
#ddl-auto=update — Spring сам создаст таблицы в БД на основе твоих классов-моделей. Добавил поле в класс — оно появится в таблице автоматически. Очень удобно на этапе разработки.
#show-sql=true — в консоли IntelliJ будешь видеть все SQL запросы которые генерирует Spring. Полезно чтобы понимать что происходит под капотом.
#/h2-console — по этому адресу в браузере можно открыть визуальный интерфейс к БД и смотреть таблицы напрямую.